server:
  port: 8083

spring:
  application:
    name: courier-app

  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write_dates_as_timestamps: false

spring.cloud.stream.kafka:
  binder:
    brokers: localhost:9092
    min-partition-count: 3
    auto-add-partitions: true
    required-acks: 1
  bindings:
    orderStatusChangeEventProcessor-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
    orderStatusChanged-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.function.definition: orderStatusChangeEventProcessor

spring.cloud.stream.bindings:
  orderStatusChangeEventProcessor-in-0:
    destination: order-status-change-events
    group: courier-app
    consumer:
      instanceCount: 3
      instanceIndex: 0

  orderStatusChangeEventProcessor-in-1:
    destination: order-status-change-events
    group: courier-app
    consumer:
      instanceCount: 3
      instanceIndex: 0

  orderStatusChangeEventProcessor-in-2:
    destination: order-status-change-events
    group: courier-app
    consumer:
      instanceCount: 3
      instanceIndex: 0

  orderStatusChangeEventProcessor-out-0:
    destination: order-status-change-events
  orderStatusChanged-out-0:
    destination: order-status-change-events
