server:
  port: 8083

spring:
  application:
    name: courier-app

  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write_dates_as_timestamps: false

spring.cloud.stream.kafka.binder:
  brokers: localhost:9092
  min-partition-count: 3
  auto-add-partitions: true

spring.cloud.stream.function.definition: orderStatusChangeEventProcessor

spring.cloud.stream.bindings:
  orderStatusChangeEventProcessor-in-0:
    destination: order-status-change-events
    group: courier-app

  orderStatusChangeEventProcessor-out-0:
    destination: order-status-change-events
  orderStatusChanged-out-0:
    destination: order-status-change-events
