server:
  port: 8082

spring:
  application:
    name: palmetto-app

  datasource:
    url: jdbc:postgresql://localhost:5432/PALMETTO_APP
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.xml

  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write_dates_as_timestamps: false


spring.cloud.stream.kafka:
  binder:
    brokers: localhost:9092
    min-partition-count: 3
    auto-add-partitions: true
    required-acks: 1
  bindings:
    orderCreateEventProcessor-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
    orderStatusChanged-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.function.definition: orderCreateEventProcessor

spring.cloud.stream.bindings:
  orderCreateEventProcessor-in-0:
    destination: order-create-events
    group: palmetto-app
    consumer:
      instanceCount: 3
      instanceIndex: 0

  orderCreateEventProcessor-in-1:
    destination: order-create-events
    group: palmetto-app
    consumer:
      instanceCount: 3
      instanceIndex: 1

  orderCreateEventProcessor-in-2:
    destination: order-create-events
    group: palmetto-app
    consumer:
      instanceCount: 3
      instanceIndex: 2

  orderCreateEventProcessor-out-0:
    destination: order-status-change-events

  orderStatusChanged-out-0:
    destination: order-status-change-events
