server:
  port: 8081

spring:
  application:
    name: client-app

  datasource:
    url: jdbc:postgresql://localhost:5432/CLIENT_APP
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.xml

  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write_dates_as_timestamps: false

spring.cloud.stream.kafka:
  binder:
    brokers: localhost:9092
    min-partition-count: 3
    auto-add-partitions: true
  bindings:
    orderCreated-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.function.definition: orderStatusChangeEventConsumer

spring.cloud.stream.bindings:
  orderCreated-out-0:
    destination: order-create-events

  orderStatusChangeEventConsumer-in-0:
    destination: order-status-change-events
    group: client-app
    consumer:
      instanceCount: 3
      instanceIndex: 0

  orderStatusChangeEventConsumer-in-1:
    destination: order-status-change-events
    group: client-app
    consumer:
      instanceCount: 3
      instanceIndex: 1

  orderStatusChangeEventConsumer-in-2:
    destination: order-status-change-events
    group: client-app
    consumer:
      instanceCount: 3
      instanceIndex: 2